spring:
  application:
    name: gateway-server
  config:
    import: "optional:configserver:"   # ✅ tell Spring to load config from Config Server
  cloud:
    config:
      uri: http://localhost:8071       # ✅ your Config Server URL
      fail-fast: true                  # (optional) make startup fail if config not reachable

management:
  endpoint:
    gateway:
#      access: read-only
      access: unrestricted            # To enable mutating operations like: /actuator/gateway/refresh
  endpoints:
    web:
      exposure:
        include: "health,info,gateway,refresh"

logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.optimagrowth: DEBUG

